baseURL = "https://KgK-16.github.io/ASCW/"
languageCode = "en"
title = "ASCW"
theme = "hugo-geekdoc"

[params]
  description = "WIP"
  geekdocNav = true
  geekdocSearch = true
  geekdocSearchPrune = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true